# Generated by Django 5.2 on 2025-04-16 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("road_id", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Roadwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extent", models.CharField(max_length=255)),
                ("identifier", models.CharField(max_length=255)),
                ("is_blocked", models.BooleanField()),
                ("title", models.CharField(max_length=255)),
                (
                    "road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadworks",
                        to="autobahn.road",
                    ),
                ),
            ],
        ),
    ]
